image: python:3.7

services:
  - name: postgres:12
    alias: db

variables:
  POSTGRES_USER: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: 5432
  SECRET_KEY: 'very_secret_key_qwerty123'

before_script:
  - python --version
  - pip install -r requirements.txt


stages:
  - Static Analysis
  - Test

pytest:
  stage: Test
  script:
    - pytest -v
