image: "python:3.7"

service:
  - postgres:12

variables:
  - POSTGRES_USER: postgres
  - POSTGRES_USER: postgres
  - POSTGRES_PASSWORD: postgres
  - POSTGRES_HOST: db
  - POSTGRES_PORT: 5432

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Test

pytest:
  stage: Test
  script:
    - pytest -v
